CTPS = {};
CTPS.mpoFinder = {};
CTPS.mpoFinder.IDENTIFY_TOLERANCE = 0.001;

CTPS.mpoFinder.szServerRoot = 'http://www.ctps.org:8080/geoserver/';
CTPS.mpoFinder.szWMSserverRoot = CTPS.mpoFinder.szServerRoot + '/wms'; 
CTPS.mpoFinder.szWFSserverRoot = CTPS.mpoFinder.szServerRoot + '/wfs';

// These are VAR's because the IE Javascript interpreter doesn't understand "const".
// Microsoft triumphs again. Ugh.
CTPS.mpoFinder.iBRPC = 0;
CTPS.mpoFinder.iFRCOG = 1;
CTPS.mpoFinder.iPVPC = 2;
CTPS.mpoFinder.iMRPC = 3;
CTPS.mpoFinder.iCMRPC = 4;
CTPS.mpoFinder.iNMCOG = 5;
CTPS.mpoFinder.iMVPC = 6;
CTPS.mpoFinder.iBMPO = 7;
CTPS.mpoFinder.iOCPC = 8;
CTPS.mpoFinder.iSRPEDD = 9;
CTPS.mpoFinder.iCCC = 10;
CTPS.mpoFinder.iMVC = 11;
CTPS.mpoFinder.iNPEDC = 12;

CTPS.mpoFinder.aMPOs = [
	{ id: CTPS.mpoFinder.iBRPC, name: "Berkshire Regional Planning Commission", kind: "MPO", 
	   url: "http://www.berkshireplanning.org" },
	{ id: CTPS.mpoFinder.iFRCG, name: "Franklin Regional Council of Governments", kind: "PO", 
	  url: "http://www.frcog.org/" },
	{ id: CTPS.mpoFinder.iPVPC, name: "Pioneer Valley Planning Commission", kind: "MPO", 
	  url: "http://www.pvpc.org" },	
	{ id: CTPS.mpoFinder.iMRPC, name: "Montachusett Regional Planning Commission", kind: "MPO", 
	  url: "http://www.mrpc.org" },
	{ id: CTPS.mpoFinder.iCMRPC, name: "Central Massachusetts Regional Planning Commission", kind: "MPO", 
	  url: "http://www.cmrpc.org" },
	{ id: CTPS.mpoFinder.iNMCOG, name: "Northern Middlesex Council of Governments", kind: "MPO", 
	  url: "http://www.nmcog.org" },
	{ id: CTPS.mpoFinder.iMVPC, name: "Merrimack Valley Planning Commission", kind: "MPO", 
	  url: "http://www.mvpc.org" },
	{ id: CTPS.mpoFinder.iBMPO, name: "Boston Region Metropolitan Planning Organization", kind: "MPO", 
	  url: "http://www.bostonmpo.org" },
    { id: CTPS.mpoFinder.iOCPC, name: "Old Colony Planning Council", kind: "MPO", 
	  url: "http://www.ocpcrpa.org" },
	{ id: CTPS.mpoFinder.iSRPEDD, name: "Southeast Regional Planning and Economic Development District" , kind: "MPO", 
	  url: "http://www.srpedd.org" },
	{ id: CTPS.mpoFinder.iCCC, name: "Cape Cod Commission", kind: "MPO", 
	  url: "http://www.capecodcommission.org" },
	{ id: CTPS.mpoFinder.iMVC, name: "Martha's Vineyard Commission", kind: "PO", 
	  url: "http://www.mvcommission.org" },
	{ id: CTPS.mpoFinder.iNPEDC, name: "Nantucket Planning and  Economic Development Commission", kind: "PO", 
	  url: "http://www.nantucket-ma.gov/pages/nantucketma_planning/npedc"}  ] ;

	  
CTPS.mpoFinder.aTownToMPOs = [
    {town_id: 1, town: "ABINGTON", mpos: [CTPS.mpoFinder.iOCPC]}, // Remember this element has array index ZERO, not one.
    {town_id: 2, town: "ACTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 3, town: "ACUSHNET", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 4, town: "ADAMS", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 5, town: "AGAWAM", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 6, town: "ALFORD", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 7, town: "AMESBURY", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 8, town: "AMHERST", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 9, town: "ANDOVER", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 10, town: "ARLINGTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 11, town: "ASHBURNHAM", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 12, town: "ASHBY", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 13, town: "ASHFIELD", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 14, town: "ASHLAND", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 15, town: "ATHOL", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 16, town: "ATTLEBORO", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 17, town: "AUBURN", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 18, town: "AVON", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 19, town: "AYER", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 20, town: "BARNSTABLE", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 21, town: "BARRE", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 22, town: "BECKET", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 23, town: "BEDFORD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 24, town: "BELCHERTOWN", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 25, town: "BELLINGHAM", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 26, town: "BELMONT", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 27, town: "BERKLEY", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 28, town: "BERLIN", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 29, town: "BERNARDSTON", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 30, town: "BEVERLY", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 31, town: "BILLERICA", mpos: [CTPS.mpoFinder.iNMCOG]},
    {town_id: 32, town: "BLACKSTONE", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 33, town: "BLANDFORD", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 34, town: "BOLTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 35, town: "BOSTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 36, town: "BOURNE", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 37, town: "BOXBOROUGH", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 38, town: "BOXFORD", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 39, town: "BOYLSTON", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 40, town: "BRAINTREE", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 41, town: "BREWSTER", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 42, town: "BRIDGEWATER", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 43, town: "BRIMFIELD", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 44, town: "BROCKTON", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 45, town: "BROOKFIELD", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 46, town: "BROOKLINE", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 47, town: "BUCKLAND", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 48, town: "BURLINGTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 49, town: "CAMBRIDGE", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 50, town: "CANTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 51, town: "CARLISLE", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 52, town: "CARVER", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 53, town: "CHARLEMONT", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 54, town: "CHARLTON", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 55, town: "CHATHAM", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 56, town: "CHELMSFORD", mpos: [CTPS.mpoFinder.iNMCOG]},
    {town_id: 57, town: "CHELSEA", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 58, town: "CHESHIRE", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 59, town: "CHESTER", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 60, town: "CHESTERFIELD", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 61, town: "CHICOPEE", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 62, town: "CHILMARK", mpos: [CTPS.mpoFinder.iMVC]},
    {town_id: 63, town: "CLARKSBURG", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 64, town: "CLINTON", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 65, town: "COHASSET", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 66, town: "COLRAIN", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 67, town: "CONCORD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 68, town: "CONWAY", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 69, town: "CUMMINGTON", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 70, town: "DALTON", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 71, town: "DANVERS", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 72, town: "DARTMOUTH", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 73, town: "DEDHAM", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 74, town: "DEERFIELD", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 75, town: "DENNIS", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 76, town: "DIGHTON", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 77, town: "DOUGLAS", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 78, town: "DOVER", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 79, town: "DRACUT", mpos: [CTPS.mpoFinder.iNMCOG]},
    {town_id: 80, town: "DUDLEY", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 81, town: "DUNSTABLE", mpos: [CTPS.mpoFinder.iNMCOG]},
    {town_id: 82, town: "DUXBURY", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 83, town: "EAST BRIDGEWATER", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 84, town: "EAST BROOKFIELD", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 85, town: "EAST LONGMEADOW", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 86, town: "EASTHAM", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 87, town: "EASTHAMPTON", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 88, town: "EASTON", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 89, town: "EDGARTOWN", mpos: [CTPS.mpoFinder.iMVC]},
    {town_id: 90, town: "EGREMONT", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 91, town: "ERVING", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 92, town: "ESSEX", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 93, town: "EVERETT", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 94, town: "FAIRHAVEN", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 95, town: "FALL RIVER", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 96, town: "FALMOUTH", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 97, town: "FITCHBURG", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 98, town: "FLORIDA", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 99, town: "FOXBOROUGH", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 100, town: "FRAMINGHAM", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 101, town: "FRANKLIN", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 102, town: "FREETOWN", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 103, town: "GARDNER", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 104, town: "AQUINNAH", mpos: [CTPS.mpoFinder.iMVC]},
    {town_id: 105, town: "GEORGETOWN", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 106, town: "GILL", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 107, town: "GLOUCESTER", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 108, town: "GOSHEN", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 109, town: "GOSNOLD", mpos: [CTPS.mpoFinder.iMVC]},
    {town_id: 110, town: "GRAFTON", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 111, town: "GRANBY", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 112, town: "GRANVILLE", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 113, town: "GREAT BARRINGTON", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 114, town: "GREENFIELD", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 115, town: "GROTON", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 116, town: "GROVELAND", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 117, town: "HADLEY", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 118, town: "HALIFAX", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 119, town: "HAMILTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 120, town: "HAMPDEN", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 121, town: "HANCOCK", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 122, town: "HANOVER", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 123, town: "HANSON", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 124, town: "HARDWICK", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 125, town: "HARVARD", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 126, town: "HARWICH", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 127, town: "HATFIELD", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 128, town: "HAVERHILL", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 129, town: "HAWLEY", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 130, town: "HEATH", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 131, town: "HINGHAM", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 132, town: "HINSDALE", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 133, town: "HOLBROOK", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 134, town: "HOLDEN", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 135, town: "HOLLAND", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 136, town: "HOLLISTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 137, town: "HOLYOKE", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 138, town: "HOPEDALE", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 139, town: "HOPKINTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 140, town: "HUBBARDSTON", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 141, town: "HUDSON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 142, town: "HULL", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 143, town: "HUNTINGTON", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 144, town: "IPSWICH", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 145, town: "KINGSTON", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 146, town: "LAKEVILLE", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 147, town: "LANCASTER", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 148, town: "LANESBOROUGH", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 149, town: "LAWRENCE", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 150, town: "LEE", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 151, town: "LEICESTER", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 152, town: "LENOX", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 153, town: "LEOMINSTER", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 154, town: "LEVERETT", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 155, town: "LEXINGTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 156, town: "LEYDEN", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 157, town: "LINCOLN", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 158, town: "LITTLETON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 159, town: "LONGMEADOW", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 160, town: "LOWELL", mpos: [CTPS.mpoFinder.iNMCOG]},
    {town_id: 161, town: "LUDLOW", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 162, town: "LUNENBURG", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 163, town: "LYNN", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 164, town: "LYNNFIELD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 165, town: "MALDEN", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 166, town: "MANCHESTER", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 167, town: "MANSFIELD", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 168, town: "MARBLEHEAD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 169, town: "MARION", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 170, town: "MARLBOROUGH", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 171, town: "MARSHFIELD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 172, town: "MASHPEE", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 173, town: "MATTAPOISETT", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 174, town: "MAYNARD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 175, town: "MEDFIELD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 176, town: "MEDFORD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 177, town: "MEDWAY", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 178, town: "MELROSE", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 179, town: "MENDON", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 180, town: "MERRIMAC", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 181, town: "METHUEN", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 182, town: "MIDDLEBOROUGH", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 183, town: "MIDDLEFIELD", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 184, town: "MIDDLETON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 185, town: "MILFORD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 186, town: "MILLBURY", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 187, town: "MILLIS", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 188, town: "MILLVILLE", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 189, town: "MILTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 190, town: "MONROE", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 191, town: "MONSON", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 192, town: "MONTAGUE", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 193, town: "MONTEREY", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 194, town: "MONTGOMERY", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 195, town: "MOUNT WASHINGTON", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 196, town: "NAHANT", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 197, town: "NANTUCKET", mpos: [CTPS.mpoFinder.iNPEDC]},
    {town_id: 198, town: "NATICK", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 199, town: "NEEDHAM", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 200, town: "NEW ASHFORD", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 201, town: "NEW BEDFORD", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 202, town: "NEW BRAINTREE", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 203, town: "NEW MARLBOROUGH", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 204, town: "NEW SALEM", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 205, town: "NEWBURY", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 206, town: "NEWBURYPORT", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 207, town: "NEWTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 208, town: "NORFOLK", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 209, town: "NORTH ADAMS", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 210, town: "NORTH ANDOVER", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 211, town: "NORTH ATTLEBOROUGH", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 212, town: "NORTH BROOKFIELD", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 213, town: "NORTH READING", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 214, town: "NORTHAMPTON", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 215, town: "NORTHBOROUGH", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 216, town: "NORTHBRIDGE", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 217, town: "NORTHFIELD", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 218, town: "NORTON", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 219, town: "NORWELL", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 220, town: "NORWOOD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 221, town: "OAK BLUFFS", mpos: [CTPS.mpoFinder.iMVC]},
    {town_id: 222, town: "OAKHAM", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 223, town: "ORANGE", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 224, town: "ORLEANS", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 225, town: "OTIS", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 226, town: "OXFORD", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 227, town: "PALMER", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 228, town: "PAXTON", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 229, town: "PEABODY", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 230, town: "PELHAM", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 231, town: "PEMBROKE", mpos: [CTPS.mpoFinder.iBMPO,CTPS.mpoFinder.iOCPC]},
    {town_id: 232, town: "PEPPERELL", mpos: [CTPS.mpoFinder.iNMCOG]},
    {town_id: 233, town: "PERU", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 234, town: "PETERSHAM", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 235, town: "PHILLIPSTON", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 236, town: "PITTSFIELD", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 237, town: "PLAINFIELD", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 238, town: "PLAINVILLE", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 239, town: "PLYMOUTH", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 240, town: "PLYMPTON", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 241, town: "PRINCETON", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 242, town: "PROVINCETOWN", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 243, town: "QUINCY", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 244, town: "RANDOLPH", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 245, town: "RAYNHAM", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 246, town: "READING", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 247, town: "REHOBOTH", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 248, town: "REVERE", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 249, town: "RICHMOND", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 250, town: "ROCHESTER", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 251, town: "ROCKLAND", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 252, town: "ROCKPORT", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 253, town: "ROWE", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 254, town: "ROWLEY", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 255, town: "ROYALSTON", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 256, town: "RUSSELL", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 257, town: "RUTLAND", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 258, town: "SALEM", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 259, town: "SALISBURY", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 260, town: "SANDISFIELD", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 261, town: "SANDWICH", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 262, town: "SAUGUS", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 263, town: "SAVOY", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 264, town: "SCITUATE", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 265, town: "SEEKONK", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 266, town: "SHARON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 267, town: "SHEFFIELD", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 268, town: "SHELBURNE", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 269, town: "SHERBORN", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 270, town: "SHIRLEY", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 271, town: "SHREWSBURY", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 272, town: "SHUTESBURY", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 273, town: "SOMERSET", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 274, town: "SOMERVILLE", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 275, town: "SOUTH HADLEY", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 276, town: "SOUTHAMPTON", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 277, town: "SOUTHBOROUGH", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 278, town: "SOUTHBRIDGE", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 279, town: "SOUTHWICK", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 280, town: "SPENCER", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 281, town: "SPRINGFIELD", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 282, town: "STERLING", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 283, town: "STOCKBRIDGE", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 284, town: "STONEHAM", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 285, town: "STOUGHTON", mpos: [CTPS.mpoFinder.iBMPO,CTPS.mpoFinder.iOCPC]},
    {town_id: 286, town: "STOW", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 287, town: "STURBRIDGE", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 288, town: "SUDBURY", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 289, town: "SUNDERLAND", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 290, town: "SUTTON", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 291, town: "SWAMPSCOTT", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 292, town: "SWANSEA", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 293, town: "TAUNTON", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 294, town: "TEMPLETON", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 295, town: "TEWKSBURY", mpos: [CTPS.mpoFinder.iNMCOG]},
    {town_id: 296, town: "TISBURY", mpos: [CTPS.mpoFinder.iMVC]},
    {town_id: 297, town: "TOLLAND", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 298, town: "TOPSFIELD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 299, town: "TOWNSEND", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 300, town: "TRURO", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 301, town: "TYNGSBOROUGH", mpos: [CTPS.mpoFinder.iNMCOG]},
    {town_id: 302, town: "TYRINGHAM", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 303, town: "UPTON", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 304, town: "UXBRIDGE", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 305, town: "WAKEFIELD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 306, town: "WALES", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 307, town: "WALPOLE", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 308, town: "WALTHAM", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 309, town: "WARE", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 310, town: "WAREHAM", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 311, town: "WARREN", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 312, town: "WARWICK", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 313, town: "WASHINGTON", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 314, town: "WATERTOWN", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 315, town: "WAYLAND", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 316, town: "WEBSTER", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 317, town: "WELLESLEY", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 318, town: "WELLFLEET", mpos: [CTPS.mpoFinder.iCCC]},
    {town_id: 319, town: "WENDELL", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 320, town: "WENHAM", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 321, town: "WEST BOYLSTON", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 322, town: "WEST BRIDGEWATER", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 323, town: "WEST BROOKFIELD", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 324, town: "WEST NEWBURY", mpos: [CTPS.mpoFinder.iMVPC]},
    {town_id: 325, town: "WEST SPRINGFIELD", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 326, town: "WEST STOCKBRIDGE", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 327, town: "WEST TISBURY", mpos: [CTPS.mpoFinder.iMVC]},
    {town_id: 328, town: "WESTBOROUGH", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 329, town: "WESTFIELD", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 330, town: "WESTFORD", mpos: [CTPS.mpoFinder.iNMCOG]},
    {town_id: 331, town: "WESTHAMPTON", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 332, town: "WESTMINSTER", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 333, town: "WESTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 334, town: "WESTPORT", mpos: [CTPS.mpoFinder.iSRPEDD]},
    {town_id: 335, town: "WESTWOOD", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 336, town: "WEYMOUTH", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 337, town: "WHATELY", mpos: [CTPS.mpoFinder.iFRCOG]},
    {town_id: 338, town: "WHITMAN", mpos: [CTPS.mpoFinder.iOCPC]},
    {town_id: 339, town: "WILBRAHAM", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 340, town: "WILLIAMSBURG", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 341, town: "WILLIAMSTOWN", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 342, town: "WILMINGTON", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 343, town: "WINCHENDON", mpos: [CTPS.mpoFinder.iMRPC]},
    {town_id: 344, town: "WINCHESTER", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 345, town: "WINDSOR", mpos: [CTPS.mpoFinder.iBRPC]},
    {town_id: 346, town: "WINTHROP", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 347, town: "WOBURN", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 348, town: "WORCESTER", mpos: [CTPS.mpoFinder.iCMRPC]},
    {town_id: 349, town: "WORTHINGTON", mpos: [CTPS.mpoFinder.iPVPC]},
    {town_id: 350, town: "WRENTHAM", mpos: [CTPS.mpoFinder.iBMPO]},
    {town_id: 351, town: "YARMOUTH", mpos: [CTPS.mpoFinder.iCCC]} ];

// This array is ordered by town name, in alphabetical order, to deal with the "Aquinnah" problem.
CTPS.mpoFinder.aTownList = [
    {town_id: 1, town: "ABINGTON"},
    {town_id: 2, town: "ACTON"},
    {town_id: 3, town: "ACUSHNET"},
    {town_id: 4, town: "ADAMS"},
    {town_id: 5, town: "AGAWAM"},
    {town_id: 6, town: "ALFORD"},
    {town_id: 7, town: "AMESBURY"},
    {town_id: 8, town: "AMHERST"},
    {town_id: 9, town: "ANDOVER"},
    {town_id: 104, town: "AQUINNAH"},
    {town_id: 10, town: "ARLINGTON"},
    {town_id: 11, town: "ASHBURNHAM"},
    {town_id: 12, town: "ASHBY"},
    {town_id: 13, town: "ASHFIELD"},
    {town_id: 14, town: "ASHLAND"},
    {town_id: 15, town: "ATHOL"},
    {town_id: 16, town: "ATTLEBORO"},
    {town_id: 17, town: "AUBURN"},
    {town_id: 18, town: "AVON"},
    {town_id: 19, town: "AYER"},
    {town_id: 20, town: "BARNSTABLE"},
    {town_id: 21, town: "BARRE"},
    {town_id: 22, town: "BECKET"},
    {town_id: 23, town: "BEDFORD"},
    {town_id: 24, town: "BELCHERTOWN"},
    {town_id: 25, town: "BELLINGHAM"},
    {town_id: 26, town: "BELMONT"},
    {town_id: 27, town: "BERKLEY"},
    {town_id: 28, town: "BERLIN"},
    {town_id: 29, town: "BERNARDSTON"},
    {town_id: 30, town: "BEVERLY"},
    {town_id: 31, town: "BILLERICA"},
    {town_id: 32, town: "BLACKSTONE"},
    {town_id: 33, town: "BLANDFORD"},
    {town_id: 34, town: "BOLTON"},
    {town_id: 35, town: "BOSTON"},
    {town_id: 36, town: "BOURNE"},
    {town_id: 37, town: "BOXBOROUGH"},
    {town_id: 38, town: "BOXFORD"},
    {town_id: 39, town: "BOYLSTON"},
    {town_id: 40, town: "BRAINTREE"},
    {town_id: 41, town: "BREWSTER"},
    {town_id: 42, town: "BRIDGEWATER"},
    {town_id: 43, town: "BRIMFIELD"},
    {town_id: 44, town: "BROCKTON"},
    {town_id: 45, town: "BROOKFIELD"},
    {town_id: 46, town: "BROOKLINE"},
    {town_id: 47, town: "BUCKLAND"},
    {town_id: 48, town: "BURLINGTON"},
    {town_id: 49, town: "CAMBRIDGE"},
    {town_id: 50, town: "CANTON"},
    {town_id: 51, town: "CARLISLE"},
    {town_id: 52, town: "CARVER"},
    {town_id: 53, town: "CHARLEMONT"},
    {town_id: 54, town: "CHARLTON"},
    {town_id: 55, town: "CHATHAM"},
    {town_id: 56, town: "CHELMSFORD"},
    {town_id: 57, town: "CHELSEA"},
    {town_id: 58, town: "CHESHIRE"},
    {town_id: 59, town: "CHESTER"},
    {town_id: 60, town: "CHESTERFIELD"},
    {town_id: 61, town: "CHICOPEE"},
    {town_id: 62, town: "CHILMARK"},
    {town_id: 63, town: "CLARKSBURG"},
    {town_id: 64, town: "CLINTON"},
    {town_id: 65, town: "COHASSET"},
    {town_id: 66, town: "COLRAIN"},
    {town_id: 67, town: "CONCORD"},
    {town_id: 68, town: "CONWAY"},
    {town_id: 69, town: "CUMMINGTON"},
    {town_id: 70, town: "DALTON"},
    {town_id: 71, town: "DANVERS"},
    {town_id: 72, town: "DARTMOUTH"},
    {town_id: 73, town: "DEDHAM"},
    {town_id: 74, town: "DEERFIELD"},
    {town_id: 75, town: "DENNIS"},
    {town_id: 76, town: "DIGHTON"},
    {town_id: 77, town: "DOUGLAS"},
    {town_id: 78, town: "DOVER"},
    {town_id: 79, town: "DRACUT"},
    {town_id: 80, town: "DUDLEY"},
    {town_id: 81, town: "DUNSTABLE"},
    {town_id: 82, town: "DUXBURY"},
    {town_id: 83, town: "EAST BRIDGEWATER"},
    {town_id: 84, town: "EAST BROOKFIELD"},
    {town_id: 85, town: "EAST LONGMEADOW"},
    {town_id: 86, town: "EASTHAM"},
    {town_id: 87, town: "EASTHAMPTON"},
    {town_id: 88, town: "EASTON"},
    {town_id: 89, town: "EDGARTOWN"},
    {town_id: 90, town: "EGREMONT"},
    {town_id: 91, town: "ERVING"},
    {town_id: 92, town: "ESSEX"},
    {town_id: 93, town: "EVERETT"},
    {town_id: 94, town: "FAIRHAVEN"},
    {town_id: 95, town: "FALL RIVER"},
    {town_id: 96, town: "FALMOUTH"},
    {town_id: 97, town: "FITCHBURG"},
    {town_id: 98, town: "FLORIDA"},
    {town_id: 99, town: "FOXBOROUGH"},
    {town_id: 100, town: "FRAMINGHAM"},
    {town_id: 101, town: "FRANKLIN"},
    {town_id: 102, town: "FREETOWN"},
    {town_id: 103, town: "GARDNER"},
    {town_id: 105, town: "GEORGETOWN"},
    {town_id: 106, town: "GILL"},
    {town_id: 107, town: "GLOUCESTER"},
    {town_id: 108, town: "GOSHEN"},
    {town_id: 109, town: "GOSNOLD"},
    {town_id: 110, town: "GRAFTON"},
    {town_id: 111, town: "GRANBY"},
    {town_id: 112, town: "GRANVILLE"},
    {town_id: 113, town: "GREAT BARRINGTON"},
    {town_id: 114, town: "GREENFIELD"},
    {town_id: 115, town: "GROTON"},
    {town_id: 116, town: "GROVELAND"},
    {town_id: 117, town: "HADLEY"},
    {town_id: 118, town: "HALIFAX"},
    {town_id: 119, town: "HAMILTON"},
    {town_id: 120, town: "HAMPDEN"},
    {town_id: 121, town: "HANCOCK"},
    {town_id: 122, town: "HANOVER"},
    {town_id: 123, town: "HANSON"},
    {town_id: 124, town: "HARDWICK"},
    {town_id: 125, town: "HARVARD"},
    {town_id: 126, town: "HARWICH"},
    {town_id: 127, town: "HATFIELD"},
    {town_id: 128, town: "HAVERHILL"},
    {town_id: 129, town: "HAWLEY"},
    {town_id: 130, town: "HEATH"},
    {town_id: 131, town: "HINGHAM"},
    {town_id: 132, town: "HINSDALE"},
    {town_id: 133, town: "HOLBROOK"},
    {town_id: 134, town: "HOLDEN"},
    {town_id: 135, town: "HOLLAND"},
    {town_id: 136, town: "HOLLISTON"},
    {town_id: 137, town: "HOLYOKE"},
    {town_id: 138, town: "HOPEDALE"},
    {town_id: 139, town: "HOPKINTON"},
    {town_id: 140, town: "HUBBARDSTON"},
    {town_id: 141, town: "HUDSON"},
    {town_id: 142, town: "HULL"},
    {town_id: 143, town: "HUNTINGTON"},
    {town_id: 144, town: "IPSWICH"},
    {town_id: 145, town: "KINGSTON"},
    {town_id: 146, town: "LAKEVILLE"},
    {town_id: 147, town: "LANCASTER"},
    {town_id: 148, town: "LANESBOROUGH"},
    {town_id: 149, town: "LAWRENCE"},
    {town_id: 150, town: "LEE"},
    {town_id: 151, town: "LEICESTER"},
    {town_id: 152, town: "LENOX"},
    {town_id: 153, town: "LEOMINSTER"},
    {town_id: 154, town: "LEVERETT"},
    {town_id: 155, town: "LEXINGTON"},
    {town_id: 156, town: "LEYDEN"},
    {town_id: 157, town: "LINCOLN"},
    {town_id: 158, town: "LITTLETON"},
    {town_id: 159, town: "LONGMEADOW"},
    {town_id: 160, town: "LOWELL"},
    {town_id: 161, town: "LUDLOW"},
    {town_id: 162, town: "LUNENBURG"},
    {town_id: 163, town: "LYNN"},
    {town_id: 164, town: "LYNNFIELD"},
    {town_id: 165, town: "MALDEN"},
    {town_id: 166, town: "MANCHESTER"},
    {town_id: 167, town: "MANSFIELD"},
    {town_id: 168, town: "MARBLEHEAD"},
    {town_id: 169, town: "MARION"},
    {town_id: 170, town: "MARLBOROUGH"},
    {town_id: 171, town: "MARSHFIELD"},
    {town_id: 172, town: "MASHPEE"},
    {town_id: 173, town: "MATTAPOISETT"},
    {town_id: 174, town: "MAYNARD"},
    {town_id: 175, town: "MEDFIELD"},
    {town_id: 176, town: "MEDFORD"},
    {town_id: 177, town: "MEDWAY"},
    {town_id: 178, town: "MELROSE"},
    {town_id: 179, town: "MENDON"},
    {town_id: 180, town: "MERRIMAC"},
    {town_id: 181, town: "METHUEN"},
    {town_id: 182, town: "MIDDLEBOROUGH"},
    {town_id: 183, town: "MIDDLEFIELD"},
    {town_id: 184, town: "MIDDLETON"},
    {town_id: 185, town: "MILFORD"},
    {town_id: 186, town: "MILLBURY"},
    {town_id: 187, town: "MILLIS"},
    {town_id: 188, town: "MILLVILLE"},
    {town_id: 189, town: "MILTON"},
    {town_id: 190, town: "MONROE"},
    {town_id: 191, town: "MONSON"},
    {town_id: 192, town: "MONTAGUE"},
    {town_id: 193, town: "MONTEREY"},
    {town_id: 194, town: "MONTGOMERY"},
    {town_id: 195, town: "MOUNT WASHINGTON"},
    {town_id: 196, town: "NAHANT"},
    {town_id: 197, town: "NANTUCKET"},
    {town_id: 198, town: "NATICK"},
    {town_id: 199, town: "NEEDHAM"},
    {town_id: 200, town: "NEW ASHFORD"},
    {town_id: 201, town: "NEW BEDFORD"},
    {town_id: 202, town: "NEW BRAINTREE"},
    {town_id: 203, town: "NEW MARLBOROUGH"},
    {town_id: 204, town: "NEW SALEM"},
    {town_id: 205, town: "NEWBURY"},
    {town_id: 206, town: "NEWBURYPORT"},
    {town_id: 207, town: "NEWTON"},
    {town_id: 208, town: "NORFOLK"},
    {town_id: 209, town: "NORTH ADAMS"},
    {town_id: 210, town: "NORTH ANDOVER"},
    {town_id: 211, town: "NORTH ATTLEBOROUGH"},
    {town_id: 212, town: "NORTH BROOKFIELD"},
    {town_id: 213, town: "NORTH READING"},
    {town_id: 214, town: "NORTHAMPTON"},
    {town_id: 215, town: "NORTHBOROUGH"},
    {town_id: 216, town: "NORTHBRIDGE"},
    {town_id: 217, town: "NORTHFIELD"},
    {town_id: 218, town: "NORTON"},
    {town_id: 219, town: "NORWELL"},
    {town_id: 220, town: "NORWOOD"},
    {town_id: 221, town: "OAK BLUFFS"},
    {town_id: 222, town: "OAKHAM"},
    {town_id: 223, town: "ORANGE"},
    {town_id: 224, town: "ORLEANS"},
    {town_id: 225, town: "OTIS"},
    {town_id: 226, town: "OXFORD"},
    {town_id: 227, town: "PALMER"},
    {town_id: 228, town: "PAXTON"},
    {town_id: 229, town: "PEABODY"},
    {town_id: 230, town: "PELHAM"},
    {town_id: 231, town: "PEMBROKE"},
    {town_id: 232, town: "PEPPERELL"},
    {town_id: 233, town: "PERU"},
    {town_id: 234, town: "PETERSHAM"},
    {town_id: 235, town: "PHILLIPSTON"},
    {town_id: 236, town: "PITTSFIELD"},
    {town_id: 237, town: "PLAINFIELD"},
    {town_id: 238, town: "PLAINVILLE"},
    {town_id: 239, town: "PLYMOUTH"},
    {town_id: 240, town: "PLYMPTON"},
    {town_id: 241, town: "PRINCETON"},
    {town_id: 242, town: "PROVINCETOWN"},
    {town_id: 243, town: "QUINCY"},
    {town_id: 244, town: "RANDOLPH"},
    {town_id: 245, town: "RAYNHAM"},
    {town_id: 246, town: "READING"},
    {town_id: 247, town: "REHOBOTH"},
    {town_id: 248, town: "REVERE"},
    {town_id: 249, town: "RICHMOND"},
    {town_id: 250, town: "ROCHESTER"},
    {town_id: 251, town: "ROCKLAND"},
    {town_id: 252, town: "ROCKPORT"},
    {town_id: 253, town: "ROWE"},
    {town_id: 254, town: "ROWLEY"},
    {town_id: 255, town: "ROYALSTON"},
    {town_id: 256, town: "RUSSELL"},
    {town_id: 257, town: "RUTLAND"},
    {town_id: 258, town: "SALEM"},
    {town_id: 259, town: "SALISBURY"},
    {town_id: 260, town: "SANDISFIELD"},
    {town_id: 261, town: "SANDWICH"},
    {town_id: 262, town: "SAUGUS"},
    {town_id: 263, town: "SAVOY"},
    {town_id: 264, town: "SCITUATE"},
    {town_id: 265, town: "SEEKONK"},
    {town_id: 266, town: "SHARON"},
    {town_id: 267, town: "SHEFFIELD"},
    {town_id: 268, town: "SHELBURNE"},
    {town_id: 269, town: "SHERBORN"},
    {town_id: 270, town: "SHIRLEY"},
    {town_id: 271, town: "SHREWSBURY"},
    {town_id: 272, town: "SHUTESBURY"},
    {town_id: 273, town: "SOMERSET"},
    {town_id: 274, town: "SOMERVILLE"},
    {town_id: 275, town: "SOUTH HADLEY"},
    {town_id: 276, town: "SOUTHAMPTON"},
    {town_id: 277, town: "SOUTHBOROUGH"},
    {town_id: 278, town: "SOUTHBRIDGE"},
    {town_id: 279, town: "SOUTHWICK"},
    {town_id: 280, town: "SPENCER"},
    {town_id: 281, town: "SPRINGFIELD"},
    {town_id: 282, town: "STERLING"},
    {town_id: 283, town: "STOCKBRIDGE"},
    {town_id: 284, town: "STONEHAM"},
    {town_id: 285, town: "STOUGHTON"},
    {town_id: 286, town: "STOW"},
    {town_id: 287, town: "STURBRIDGE"},
    {town_id: 288, town: "SUDBURY"},
    {town_id: 289, town: "SUNDERLAND"},
    {town_id: 290, town: "SUTTON"},
    {town_id: 291, town: "SWAMPSCOTT"},
    {town_id: 292, town: "SWANSEA"},
    {town_id: 293, town: "TAUNTON"},
    {town_id: 294, town: "TEMPLETON"},
    {town_id: 295, town: "TEWKSBURY"},
    {town_id: 296, town: "TISBURY"},
    {town_id: 297, town: "TOLLAND"},
    {town_id: 298, town: "TOPSFIELD"},
    {town_id: 299, town: "TOWNSEND"},
    {town_id: 300, town: "TRURO"},
    {town_id: 301, town: "TYNGSBOROUGH"},
    {town_id: 302, town: "TYRINGHAM"},
    {town_id: 303, town: "UPTON"},
    {town_id: 304, town: "UXBRIDGE"},
    {town_id: 305, town: "WAKEFIELD"},
    {town_id: 306, town: "WALES"},
    {town_id: 307, town: "WALPOLE"},
    {town_id: 308, town: "WALTHAM"},
    {town_id: 309, town: "WARE"},
    {town_id: 310, town: "WAREHAM"},
    {town_id: 311, town: "WARREN"},
    {town_id: 312, town: "WARWICK"},
    {town_id: 313, town: "WASHINGTON"},
    {town_id: 314, town: "WATERTOWN"},
    {town_id: 315, town: "WAYLAND"},
    {town_id: 316, town: "WEBSTER"},
    {town_id: 317, town: "WELLESLEY"},
    {town_id: 318, town: "WELLFLEET"},
    {town_id: 319, town: "WENDELL"},
    {town_id: 320, town: "WENHAM"},
    {town_id: 321, town: "WEST BOYLSTON"},
    {town_id: 322, town: "WEST BRIDGEWATER"},
    {town_id: 323, town: "WEST BROOKFIELD"},
    {town_id: 324, town: "WEST NEWBURY"},
    {town_id: 325, town: "WEST SPRINGFIELD"},
    {town_id: 326, town: "WEST STOCKBRIDGE"},
    {town_id: 327, town: "WEST TISBURY"},
    {town_id: 328, town: "WESTBOROUGH"},
    {town_id: 329, town: "WESTFIELD"},
    {town_id: 330, town: "WESTFORD"},
    {town_id: 331, town: "WESTHAMPTON"},
    {town_id: 332, town: "WESTMINSTER"},
    {town_id: 333, town: "WESTON"},
    {town_id: 334, town: "WESTPORT"},
    {town_id: 335, town: "WESTWOOD"},
    {town_id: 336, town: "WEYMOUTH"},
    {town_id: 337, town: "WHATELY"},
    {town_id: 338, town: "WHITMAN"},
    {town_id: 339, town: "WILBRAHAM"},
    {town_id: 340, town: "WILLIAMSBURG"},
    {town_id: 341, town: "WILLIAMSTOWN"},
    {town_id: 342, town: "WILMINGTON"},
    {town_id: 343, town: "WINCHENDON"},
    {town_id: 344, town: "WINCHESTER"},
    {town_id: 345, town: "WINDSOR"},
    {town_id: 346, town: "WINTHROP"},
    {town_id: 347, town: "WOBURN"},
    {town_id: 348, town: "WORCESTER"},
    {town_id: 349, town: "WORTHINGTON"},
    {town_id: 350, town: "WRENTHAM"},
    {town_id: 351, town: "YARMOUTH"}];

	
CTPS.mpoFinder.init = function() {
	
	CTPS.mpoFinder.map = new OpenLayers.Map('map',
		{
			'projection'     : 'EPSG:26986',
			'maxResolution'  : 2000,
			'maxExtent'      : new OpenLayers.Bounds(33861.264,777514.311,330846.093,959747.441),
			'units'          : 'm',
			'fractionalZoom' : true,
			'controls'       : []   // This causes the default NavigationControl NOT to be loaded.
		}
	);

	var oBaseLayer = new OpenLayers.Layer.WMS.Untiled(
		"Base Layer",
		CTPS.mpoFinder.szWMSserverRoot,
		{layers: 'postgis:mgis_rpas_poly,postgis:mgis_towns_polym',
		 styles: 'rpas_poly,polygon'} 
	);
	
	var oStyleHighlightedTown = new OpenLayers.Style( {'fillColor': "#F88017", 'strokeWidth': 2 });
	CTPS.mpoFinder.oHighlightLayer = new OpenLayers.Layer.Vector(
		"Highlighted Town",
		{
			styleMap: oStyleHighlightedTown
		}
	);
	
	CTPS.mpoFinder.map.addLayers([oBaseLayer,CTPS.mpoFinder.oHighlightLayer]);
	// CTPS.mpoFinder.map.addControl(new OpenLayers.Control.LayerSwitcher());
	
	// Add scale control - for SLD development/debugging.
	// var oScale = new OpenLayers.Control.Scale();
	// CTPS.mpoFinder.map.addControl(oScale);
	
	// Add ScaleBar add-in control
	var oScalebar = new OpenLayers.Control.ScaleBar();
	oScalebar.displaySystem = 'english';
	oScalebar.divisions = 2;
	oScalebar.subdivisions = 2;
	oScalebar.showMinorMeasures = false;
	oScalebar.singleLine = false;
	oScalebar.abbreviateLabel = false;
	CTPS.mpoFinder.map.addControl(oScalebar);
	
	CTPS.mpoFinder.map.zoomToMaxExtent();
	
	// Populate pull-down list of towns in Massachusetts.
	var i = 0;
	var oOption = {};
	for (i = 0; i < CTPS.mpoFinder.aTownList.length; i++) {
		oOption = document.createElement("OPTION");
		oOption.text = CTPS.mpoFinder.aTownList[i].town;
		oOption.value = CTPS.mpoFinder.aTownList[i].town_id;
		document.app_form.town_list.options.add(oOption);
	}
	
	CTPS.mpoFinder.map.events.register(
		'click',
		null,
		CTPS.mpoFinder.onClickHandler);

}; // CTPS.mpoFinder.init()

CTPS.mpoFinder.getMposForTown = function(iTownId) {
    // Note: iTownId = document.getElementById('selected_town').value;
	var aTemp = [];
	var szAll = ""; // The entire new "innerHTML".
	var szLine = "";
	var szHeader = "";
	var szName = "";
	var szUrl = "";
	var iMpoId = 0;
	var i = 0;	
	var eOutputDiv = document.getElementById("output_div");
	
	// Clear any highlighted features on the map.
	CTPS.mpoFinder.oHighlightLayer.destroyFeatures();
	
	if (iTownId > 0) {
		aTemp = CTPS.mpoFinder.aTownToMPOs[iTownId-1].mpos;
		// This is a bit of a hack, but it works. Here's why:
		// Strictly speaking we should iterate over all the MPOs in aTemp, looking at their "kind".
		// However, aTemp will have a length > 1 for only two towns in the state. In both cases,
		// all the MPOs these towns belong to really are *M*POs, rather than plain vanilla POs.
		szHeader = (CTPS.mpoFinder.aMPOs[aTemp[0]].kind === "MPO") ? "Metropolitan " : "";
		szHeader += "Planning Organization ";
		szHeader +=  (aTemp.length > 1) ? "websites" : "website"; 
		szHeader += " for " + CTPS.mpoFinder.aTownToMPOs[iTownId-1].town + ":";
		szAll = szHeader;
		szAll += "<br>";
		for (i = 0; i < aTemp.length; i++) {
			iMpoId = aTemp[i];
			szName = CTPS.mpoFinder.aMPOs[iMpoId].name;
			szUrl = CTPS.mpoFinder.aMPOs[iMpoId].url;
			szLine = '<a href=' ;
			szLine += '\"';
			szLine += szUrl;
			szLine += '\" ';
			szLine += 'target=';
			szLine += '\"_blank\">';
			szLine += szName;
			szLine += '<\a>';
			szAll += szLine + "<br>";
		}
		eOutputDiv.innerHTML = szAll;
		CTPS.mpoFinder.highlightTown(iTownId);
	} else {
		eOutputDiv.innerHTML = "";
	}
}; // CTPS.mpoFinder.getMposForTown()

CTPS.mpoFinder.highlightTown = function(iTownId) {
	var cqlFilter = "(town_id=" + iTownId + ")";
	OpenLayers.Request.issue({
			'method': 'GET',
			'url': CTPS.mpoFinder.szWFSserverRoot,
			'params': {
				service: 'WFS',
				version: '1.0.0',
				typename: 'postgis:mgis_towns_polym',
				request: 'getfeature',
				cql_filter: cqlFilter
			},
			'headers': {'content-type' : 'application/xml'},
			'success': function(oRequest) {
				var g = new OpenLayers.Format.GML();
				var aFeatures = g.read(oRequest.responseText);
				if (aFeatures.length === 0) {
					alert("No town with that name found.");
					return;
				}				
				// CTPS.mpoFinder.oHighlightLayer.destroyFeatures();
				CTPS.mpoFinder.oHighlightLayer.addFeatures(aFeatures);
			},
			'failure': function(oRequest) {
				alert("WFS request A failed.");
			}
		});
}; // CTPS.mpoFinder.highlightTown()

CTPS.mpoFinder.onClickHandler = function(e) {
	var szQueryString = CTPS.mpoFinder.szWFSserverRoot  + '?';
	szQueryString += "request=getfeature&version=1.0.0&service=wfs&";
	szQueryString += "typename=postgis:mgis_towns_polym";
	
	var oLonLat = CTPS.mpoFinder.map.getLonLatFromPixel(e.xy);
	var szFilter = '&cql_filter=(INTERSECTS(wkb_geometry,POINT(' + oLonLat.lon + ' ' + oLonLat.lat + ')))';
	szQueryString += szFilter;

	OpenLayers.Request.issue({
			method: "GET",
			url: szQueryString,
			success: function(oRequest) {
				var oGmlReader = new OpenLayers.Format.GML();
				var aFeatures = oGmlReader.read(oRequest.responseText);
				if (aFeatures.length !== 0) {
					// alert(aFeatures[0].attributes['town'] + " " + aFeatures[0].attributes['town_id']);
					CTPS.mpoFinder.getMposForTown(aFeatures[0].attributes['town_id']);
					// Clear out the list-box choice, in case any town was selected.
					// Leaving the name of (another) town there could be confusing to the user.
					document.getElementById('selected_town').selectedIndex = 0;
				} else {
					var __DEBUG_HOOK__ = 0; // "Fail" silently if user clicked outside of a MA town.
				}
			},
			failure: function() {
				alert('WFS request B failed.');
			}
	});
}; // CTPS.mpoFinder.onClickHandler()
